### ISSUE TITLE
Rekursion funktioniert nicht

### ISSUE THREAD

**Issue by Hueppy** [Compiler-CampusMinden/Mini-Python-Builder#1]
Bei der Verwendung von Rekursion scheint es noch ein Problem zu geben, weshalb sich der generierte C-Quellcode nicht kompilieren lässt.

In Anbetracht des folgenden Java-Beispiels:
```java
import CBuilder.ProgramBuilder;
import CBuilder.Reference;
import CBuilder.objects.Call;
import CBuilder.objects.functions.Function;

import java.nio.file.Path;
import java.util.List;

public class Program {
    public static void main(String[] args) {
        ProgramBuilder programBuilder = new ProgramBuilder();

        programBuilder.addFunction(new Function(
                "f",
                List.of(new Call(new Reference("f"), List.of())),
                List.of(),
                List.of()));

        programBuilder.writeProgram(Path.of("out"));
    }
}
```

Landet im generierten C-Quellcode die Deklaration des Objektes `f` hinter der Implementierung der Funktion `func_f`
```c
__MPyObj* func_f(__MPyObj *args, __MPyObj *kwargs) {
	assert(args != NULL && kwargs != NULL);
	
	__MPyGetArgsState argHelper = __mpy_args_init("f", args, kwargs, 0);
	__mpy_args_finish(&argHelper);
	
	__MPyObj *retValue = NULL;
	
	__mpy_obj_ref_dec(__mpy_call(f, __mpy_obj_init_tuple(0), NULL));
	
	
	goto ret;
	ret:
	if (retValue == NULL) {
		retValue = __mpy_obj_init_object();
	}
	return __mpy_obj_return(retValue);
}
__MPyObj *f;
```

Beim Builden des generierten C-Quellcodes wird dadurch folgende Fehlermeldung geworfen (GCC 11):
```gcc
out/src/program.c:24:38: error: ‘f’ undeclared (first use in this function)
   24 |         __mpy_obj_ref_dec(__mpy_call(f, __mpy_obj_init_tuple(0), NULL));
      | 
```

Verschiebe ich nun manuell im C-Quellcode die Deklaration von `f` vor die Implementierung `func_f` läuft das Build erfolgreich durch und die Ausführung scheint korrekt zu funktionieren.

**Comment by cagix** [comment]
@CrappyAlgorithm Kannst Du bitte kurz reinschauen?

**Comment by CrappyAlgorithm** [comment]
> @CrappyAlgorithm Kannst Du bitte kurz reinschauen?

Ich schaue mal, ob ich da gegen Abend Zeit für finde. Ansonsten kümmere ich mich morgen darum.

**Comment by cagix** [comment]
das wäre super. ich komme auch frühestens morgen dazu ... und mir kommt das grad etwas seltsam vor, das müsste ja bei normalen nicht-rekursiven funktionen dann auch so sein und schon mal wo auf die füße gefallen sein?  

und eine forwärts-deklaration im c-code direkt nach der definition macht prinzipiell irgendwie wenig sinn aus meiner sicht.

**Comment by cagix** [comment]
@CrappyAlgorithm Ich würde die beiden Zeilen https://github.com/Compiler-CampusMinden/Mini-Python-Builder/blob/dfd40c905445ed8569645f730768d96f38e45687/src/main/java/CBuilder/ProgramBuilder.java#L142-L143 vertauschen - dann würde die Reihenfolge genauso, wie es @Hueppy beschrieben hat (und wie es für C sinnvoll wäre). Ich bin nur grad unsicher, ob ich damit nicht was kaputt mache, weil diese Lösung ja früher schon mal hätte auffallen müssen?

**Comment by cagix** [comment]
@liketechnik Falls Du zufällig mitliest: Mache ich mit https://github.com/Compiler-CampusMinden/Mini-Python-Builder/issues/1#issuecomment-1351241893 was kaputt?

**Comment by liketechnik** [comment]
TL~DR: Zum Reparieren der Rekursion reicht der oben beschriebene Fix. Soll der allgemeine Fall des Aufrufs einer erst später deklarierten Funktion gefixt werden, müssen zuerst alle Vorwärtsdeklaration und erst danach die C-Implementierung der Funktionen generiert werden.

---

> Mache ich mit https://github.com/Compiler-CampusMinden/Mini-Python-Builder/issues/1#issuecomment-1351241893 was kaputt?

Nein. Aber auch, wie bereits befürchtet, auch noch nicht alles wieder in Ordnung:

> das müsste ja bei normalen nicht-rekursiven funktionen dann auch so sein und schon mal wo auf die füße gefallen sein?

Ja (also es ist auch bei nicht-rekursiven Funktionen so. Auf die Füße gefallen wohl leider nicht). Beispiel:
``` python
def first():
    second()

def second():
    print("second")
```
wird zu 
``` c
__MPyObj* func_first(__MPyObj *args, __MPyObj *kwargs) {
	assert(args != NULL && kwargs != NULL);
	
	__MPyGetArgsState argHelper = __mpy_args_init("f", args, kwargs, 0);
	__mpy_args_finish(&argHelper);
	
	__MPyObj *retValue = NULL;
	
	__mpy_obj_ref_dec(__mpy_call(second, __mpy_obj_init_tuple(0), NULL));
	
	
	goto ret;
	ret:
	if (retValue == NULL) {
		retValue = __mpy_obj_init_object();
	}
	return __mpy_obj_return(retValue);
}
__MPyObj *first;

__MPyObj* func_second(__MPyObj *args, __MPyObj *kwargs) {
	assert(args != NULL && kwargs != NULL);
	
	__MPyGetArgsState argHelper = __mpy_args_init("f", args, kwargs, 0);
	__mpy_args_finish(&argHelper);
	
	__MPyObj *retValue = NULL;
	
	__mpy_obj_ref_dec(__mpy_call(print, __mpy_tuple_set(1, "__mpy_obj_init_tuple(1), NULL));
	
	
	goto ret;
	ret:
	if (retValue == NULL) {
		retValue = __mpy_obj_init_object();
	}
	return __mpy_obj_return(retValue);
}
__MPyObj *second;
```
(ich habe das jetzt nicht in dem CBuilder geworfen, sondern einfach den Code von oben kopiert und angepasst. Kann also sein das das nicht exakt so generiert wird -- und daher auch wg. typos nicht kompilieren würde)

Da es `second` aber noch nicht gibt, kommt im Prinzip der selbe Fehler bei raus:
```
out/src/program.c:??:??: error: ‘second’ undeclared (first use in this function)
   24 |         __mpy_obj_ref_dec(__mpy_call(second, __mpy_obj_init_tuple(0), NULL));
      | 
```

---

Grundproblem ist hierbei, dass ich bei der Implementierung nicht daran gedacht habe, dass ich ja auch erst später deklarierte Funktionen aufrufen können muss. Daher steht die Deklaration des MiniPython-Funktion-Objekts einfach hinter der C-Implementierung selber -- was zu den beiden gezeigten Fehlern führt (1. Rekursion -- dieser Issue 2. Reihenfolge von Funktionen die einander aufrufen -- mein Beispiel hier).

Für die Rekursion reicht der Fix von @cagix mit dem Verschieben der Zeilen [^1].

Für den allgemeineren Fall ist es nicht ganz so einfach. Wie im vorherigen Kommentar von @cagix bemerkt, generiert der Builder im Prinzip Implementierung (C-Funktion) und Vorwärtsdeklaration [^2] (eigentlich MiniPython Objekt, s.o.). Um das hier gezeigte Problem zu lösen muss, wie bereits gesagt (siehe Rekursion), die Vorwärtsdeklaration vor der Implementierung kommen. Für den allgemeinen Fall aber halt nicht mehr nur spezifisch für die gerade generierte Funktion, sondern für alle Funktionen. Und das heißt, aus der einen Funktion, welche die beide Aufrufe `f.buildCFunction(); f.buildFuncObjectDeclaration();` macht, müssen zwei werden, die folgende Aufrufe machen:

1. die erste ruft `f.buildFuncObjectDeclaration();` auf
2. die zweite `f.buildCFunction();`

(wobei "ruft `f.buildBla()` auf" vereinfacht steht für "ruft `f.buildBla()` auf und fügt den Rückgabe-String an der richtigen Stelle (z. B. `program`) an")


[^1]: https://github.com/Compiler-CampusMinden/Mini-Python-Builder/issues/1#issuecomment-1351241893
[^2]: https://github.com/Compiler-CampusMinden/Mini-Python-Builder/issues/1#issuecomment-1350807475

**Comment by cagix** [comment]
> Und das heißt, aus der einen Funktion, welche die beide Aufrufe f.buildCFunction(); f.buildFuncObjectDeclaration(); macht, müssen zwei werden, die folgende Aufrufe machen:

@liketechnik Danke fürs Feedback! Dann haben wir einen Quickfix als schnelle Lösung für das Problem hier. 

Und für später könnte man ja tatsächlich im generierten Code einmal ziemlich am Anfang über die Funktionsobjekte itererieren und `f.buildFuncObjectDeclaration()` aufrufen und dann später dann die eigentliche Definition `f.buildCFunction()` ... d.h. man müsste eigentlich "nur" die jetzige Iteration aufsplitten...

**Comment by cagix** [comment]
@Hueppy Das Issue sollte mit 902fd00 behoben sein. Bitte prüfen und das Ticket ggf. noch einmal aufmachen.

**Comment by Hueppy** [comment]
Unser Rekursionsbeispiel funktioniert jetzt ohne manuelle Änderungen am generierten Source. :+1: 
Das Ticket kann also geschlossen bleiben.

**Comment by cagix** [comment]
danke für das feedback :) 

... und bitte auch #2 beachten, so ganz komplett ist das noch nicht gelöst. aber ohne testsuite wollte ich da nicht dran 🙈🤣
